import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";
import {
  FacebookIcon,
  GithubIcon,
  InstagramIcon,
  TwitterIcon,
} from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AsipreAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning>
        <ClerkProvider appearance={{ baseTheme: dark }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />
            <main className="min-h-screen"> {children}</main>
            <Toaster richColors />

            {/* footer */}
            <footer className="bg-muted/50 py-10 mt-12">
              <div className="container mx-auto text-center text-gray-400">
                <p className="text-lg font-semibold flex items-center justify-center space-x-2">
                  Made with{" "}
                  <span className="text-red-500 animate-pulse">❤️</span> by
                  <span className="font-bold text-gray-300">Kirigaya07</span>
                </p>

                <div className="flex justify-center space-x-6 mt-4 text-sm">
                  <a
                    href="#"
                    className="hover:text-primary transition duration-300"
                  >
                    Home
                  </a>
                  <a
                    href="#"
                    className="hover:text-primary transition duration-300"
                  >
                    About
                  </a>
                  <a
                    href="#"
                    className="hover:text-primary transition duration-300"
                  >
                    Contact
                  </a>
                  <a
                    href="#"
                    className="hover:text-primary transition duration-300"
                  >
                    Privacy
                  </a>
                </div>

                <div className="mt-6 flex justify-center space-x-4">
                  <a href="#" className="hover:text-blue-500 transition">
                    <FacebookIcon className="h-5 w-5" />
                  </a>
                  <a href="#" className="hover:text-blue-400 transition">
                    <TwitterIcon className="h-5 w-5" />
                  </a>
                  <a href="#" className="hover:text-gray-500 transition">
                    <GithubIcon className="h-5 w-5" />
                  </a>
                  <a href="#" className="hover:text-pink-500 transition">
                    <InstagramIcon className="h-5 w-5" />
                  </a>
                </div>

                <p className="text-xs text-gray-500 mt-6">
                  © {new Date().getFullYear()} Kirigaya07. All rights reserved.
                </p>
              </div>
            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
